apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    name: nginx-1
spec:
  containers:
  - name: nginx-1
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    name: nginx-2
spec:
  containers:
  - name: nginx-2
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
