apiVersion: apps/v1
kind: Deployment
metadata:
  name: service4
spec:
  selector:
    matchLabels:
      app: service4
  replicas: 1
  template:
    metadata:
      labels:
        app: service4
    spec:
      containers:
      - name: service4
        image: omriselda/app4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: service4
spec:
  selector:
    app: service4
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
  type: ClusterIP


