apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp4
spec:
  selector:
    matchLabels:
      app: myapp4
  replicas: 
  template:
    metadata:
      labels:
        app: myapp4
    spec:
      containers:
      - name: myapp4
        image: omriselda/app4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: myapp4
spec:
  selector:
    app: myapp4
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
  type: LoadBalancer

