apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
spec:
  selector:
    matchLabels:
      app: service3
  replicas: 1
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: omriselda/app3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: service3
spec:
  selector:
    app: service3
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
  type: ClusterIP


