apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: security-context-vol
  emptyDir: {}
  containers:
  - name: security-context-demo
    image: busybox
    command: ["sh","-c","sleep 1h"]
    volumemounts:
    - name: security-context-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
