# Normally this should NOT be on GitHub, but for tutorial purposes this one is
apiVersion: v1
kind: Secret
metadata:
  name: secret-key
type: Opaque
stringData:
  secretKey: {{secretKey}}

# Apply the secret with this command in the terminal:
# sed 's/{{secretKey}}/280owegfowuye/g' secret.yaml | kubectl apply -f -